Update build-image

diff --git a/build-image b/build-image
--- a/build-image
+++ b/build-image
@@ -20,6 +20,12 @@ TARGET_DEVICE=$1
 MINIMALPI_GIT_URL="https://github.com/JPG-Consulting/MinimalPi.git"
 MINIMALPI_GIT_BRANCH="development"
 
+# Networking
+#-----------------------------------------------------------
+NETWORK_ADDRESS="192.168.1.3"
+NETWORK_NETMASK="255.255.255.0"
+NETWORK_GATEWAY="192.168.1.1"
+
 # Functions
 #-----------------------------------------------------------
 is_host_arm() {
@@ -377,20 +383,43 @@ ff02::2		ip6-allrouters
 EOF
 fi
 
-LANG=C chroot ${CHROOT_DIR} apt-get -y install isc-dhcp-client
-if [ $? -ne 0 ]; then
-    do_unmount_partitions
-    do_unset_partitions
-    echo "Error: Unable to install dhcp client."
-    exit 1
-fi
-
-cat <<EOF > ${CHROOT_DIR}/etc/network/interfaces
+if [ -n "${NETWORK_ADDRESS}" ]; then
+    IFS=. read -r i1 i2 i3 i4 <<< "${NETWORK_ADDRESS}"
+    IFS=. read -r m1 m2 m3 m4 <<< "${NETWORK_NETMASK}"
+    network_network=$(printf "%d.%d.%d.%d" "$((i1 & m1))" "$((i2 & m2))" "$((i3 & m3))" "$((i4 & m4))")
+    network_broadcast=$(printf "%d.%d.%d.%d" "$((i1 | (255 ^ m1)))" "$((i2 | (255 ^ m2)))" "$((i3 | (255 ^ m3)))" "$((i4 | (255 ^ m4)))")
+    
+    cat <<EOF > ${CHROOT_DIR}/etc/network/interfaces
 auto lo
 iface lo inet loopback
+
+auto eth0
+iface eth0 inet static
+  address ${NETWORK_ADDRESS}
+  netmask ${NETWORK_NETMASK}
+  network ${network_network}
+  broadcast ${network_broadcast}
+  gateway ${NETWORK_GATEWAY}
+EOF
+fi
+
+if [ -n "${NETWORK_ADDRESS}" ]; then
+    LANG=C chroot ${CHROOT_DIR} apt-get -y install isc-dhcp-client
+    if [ $? -ne 0 ]; then
+        do_unmount_partitions
+        do_unset_partitions
+        echo "Error: Unable to install dhcp client."
+        exit 1
+    fi
+
+    cat <<EOF > ${CHROOT_DIR}/etc/network/interfaces
+auto lo
+iface lo inet loopback
+
 auto eth0
 iface eth0 inet dhcp
 EOF
+fi
 
 cat <<EOF > ${CHROOT_DIR}/etc/fstab
 proc            /proc           proc    defaults          0       0
